# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
